"""followers

Revision ID: 884df3d8bdf1
Revises: 1a434680a3ba
Create Date: 2019-01-31 21:37:45.977096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884df3d8bdf1'
down_revision = '1a434680a3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
